### ISSUE TITLE
[Not an issue] Consider porting to SmsSender

### ISSUE THREAD

**Issue by kbsali** [econic/Mobilant#1]
Hi,

Please, consider integrating this provider to https://github.com/Carpe-Hora/SmsSender which tries to aggregate different SMS providers!

Thanks! :)

**Comment by econic** [comment]
I'm currently about to composerize it anyways, so i could make it depend on https://packagist.org/packages/Carpe-Hora/SmsSender nicely.
I'll have a look at it, thanks!
